### ISSUE TITLE
Caching image at different sizes?

### ISSUE THREAD

**Issue by britannio** [humblerookie/optimized_cached_image#13]
I'm downloading a full-size image then using `OptimizedCacheImage` to cache a downsized version but then when I want to view the full-size image it sees that the width and height are different so the download is performed again. 

Is there a way to download the image once and save it at different resolutions so I can show the same image at two resolutions with a single download?

e.g. download an image at 1000x1000 then save it at 1000x1000 and at 100x100. That way I can smoothly show a list of 100x100 images but also view a full 1000x1000 image on its own.

Would it be sensible to add a `List<Size> cacheSizes;` property to `OptimizedCacheImage`?

Thanks!

**Comment by zamahaka** [comment]
@britannio This is mentioned id [Readme](https://github.com/humblerookie/optimized_cached_image/blob/master/README.md) Todo section.

> Prevent same url from being downloaded multiple times for different image sizes

**Comment by britannio** [comment]
> @britannio This is mentioned in [Readme](https://github.com/humblerookie/optimized_cached_image/blob/master/README.md) Todo section.
> 
> > Prevent same url from being downloaded multiple times for different image sizes

Yeah, is it being addressed soon? Do you have any guidance if I were to attempt to implement it?

**Comment by humblerookie** [comment]
https://github.com/humblerookie/optimized_cached_image/pull/20 address the same, I've made a prerelease `1.0.0-beta` for the same. I'm closing this issue, for now, feel free to open if you feel otherwise.
