### ISSUE TITLE
Exception: Could not instantiate image codec.

### ISSUE THREAD

**Issue by amitjangid80** [humblerookie/optimized_cached_image#16]
I get this error while loading images using this plugin. The image is loading from the url, but when I close the app and open again then I get this error. The images are loaded and displaying properly but after closing and re-opening the app I get these error.

Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4304:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
#2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:653:24)
<asynchronous suspension>
...
Path: /data/user/0/appPackageName/cache/libCachedImageData/e65291e0-c273-11ea-918b-35fb95148e5f.jpg

**Comment by humblerookie** [comment]
Hi Amit
Thanks for highlighting the issue, I'll take a look. Could you specify the entire stacktrace in the meantime?

**Comment by amitjangid80** [comment]
Hi, 

This is the only stacktrace I got. But, sometimes I get the following exception as well.

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following _Exception was thrown resolving an image codec:
flutter: Exception: Could not instantiate image codec.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _futurize (dart:ui/painting.dart:4304:5)
flutter: #1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
flutter: #2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
flutter: #3      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:653:24)
flutter: <asynchronous suspension>
flutter: #4      FileImage.load (package:flutter/src/painting/image_provider.dart:638:14)
flutter: #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
flutter: #6      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
flutter: #7      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:325:84)
flutter: #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #9      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:323:11)
flutter: #13     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:315:16)
flutter: #14     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1010:20)
flutter: #15     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:967:5)
flutter: #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
flutter: #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
flutter: #30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
flutter: #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
flutter: #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #43     _invoke (dart:ui/hooks.dart:259:10)
flutter: #44     _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 6 frames from package dart:async)
flutter:
flutter: Path:
flutter: /Users/username/Library/Developer/CoreSimulator/Devices/DF40A4DA-6CB1-4FAD-A7F8-C76F1EC885F7/data/Containers/Data/Application/4640186F-A6FE-40D8-BE8E-1ECF4A3577B9/Library/Caches/libCachedImageData/7cab66d0-c288-11ea-a22f-d7949748ba84.jpg

**Comment by leszekkrol** [comment]
Any update in this case?

**Comment by humblerookie** [comment]
@leszekkrol  Not yet. I'll check and post back.

**Comment by humblerookie** [comment]
@leszekkrol  and @amitjangid80  Can you turn [enableLog](https://github.com/humblerookie/optimized_cached_image/blob/647a3da4f96d34cf1273c88fb98b932b0b55830d/example/lib/main.dart#L26) flag and share the logs?

**Comment by humblerookie** [comment]
Seems like there was a similar [issue](https://github.com/Baseflow/flutter_cached_network_image/issues/320) which was fixed in the parent project .I've synced with the project and updated a new version let me know if this fixes the issue

**Comment by humblerookie** [comment]
I'm closing this issue dude to inactivity, feel free to reopen in case the issue resurfaces
