### ISSUE TITLE
Image doesn't load when file in cache is unavailable

### ISSUE THREAD

**Issue by dev-kasibhatla** [humblerookie/optimized_cached_image#17]
For some reason, from time to time, one or more files in cache get invalidated / corrupted and while it doesn't crash the app, the image container remains empty.
The thrown exception is printed onto the console:

Here is the error for your reference:

` Bad state: LocalFile: '/data/user/0/***/cache/libCachedImageData/****-d018-11ea-9ac9-19b2fc1cd3e3.jpg' is empty and cannot be loaded as an image. `

```
When the exception was thrown, this was the stack: 
      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:859:7)
<asynchronous suspension>
      FileImage.load (package:flutter/src/painting/image_provider.dart:843:14)
      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22) 
```

Similar error was encountered by people using a similar package and was recently fixed.
Please look [here](https://github.com/Baseflow/flutter_cached_network_image/issues/320)

Hoping for a quick fix / solution

**Comment by humblerookie** [comment]
Hey, thanks for bringing this up. I'll take a look and patch this.

**Comment by JayPerfetto** [comment]
I also have this issue, thanks

**Comment by humblerookie** [comment]
I've synced up this repo with the parent project. Could you verify if the issue still persists?

**Comment by dev-kasibhatla** [comment]
I couldn't find a way to reproduce the error, and i think it is fairly random. If anyone finds out that the issue persists, please reopen this thread.
Thank you

**Comment by humblerookie** [comment]
thanks a lot :)
