### ISSUE TITLE
Should this package be depending on the octo_image package instead of copy/pasting it.

### ISSUE THREAD

**Issue by britannio** [humblerookie/optimized_cached_image#21]
I'd think that it would be easier to keep this package up to date with `cached_network_image` if it copied the least amount of code. Since `octo_image` is a package on pub and it doesn't affect caching, wouldn't it be better to just depend on the package itself?

**Comment by humblerookie** [comment]
[This PR](https://github.com/humblerookie/optimized_cached_image/pull/22) should resolve the same
