### ISSUE TITLE
Please add cancellation function

### ISSUE THREAD

**Issue by kokocooler2020** [humblerookie/optimized_cached_image#25]
This is a high-performance plugin, but no cancellation function.
When a lot of image in a list view, and user scrolling it fast, a lot of network or file load will cause lag.
so, whould you thinking for add cancellation function please? 
The cancellation function will bring amazing performance and load capacity!
and thank you!

**Comment by humblerookie** [comment]
@kokocooler2020 Thanks for notifying this, while I could make the necessary changes here I think this use case fits the parent library so I'd recommend raising an issue over there instead.

**Comment by humblerookie** [comment]
Closing this issue after no response
