### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by zierka** [humblerookie/optimized_cached_image#28]
After switching from [cached_network_image](https://pub.dev/packages/cached_network_image) I found that gif-s aren't playing anymore. Flutter `Image` natively supports playing gif-s, it would be nice if this (otherwise really great!) package could support it as well.

**Comment by humblerookie** [comment]
@zierka  This is primarily because of the compression library support, while `flutter_cached_network_image` uses `image` to compress I'm using `flutter_image_compress` which seems to be a little more efficient. I'll add `image` as a fallback since the other library doesn't support gifs

**Comment by humblerookie** [comment]
Hi @zierka, I've included limited support for gifs via webp via https://github.com/humblerookie/optimized_cached_image/pull/42. Do take a look at the prerelease version `2.0.2-alpha` and let me know if that works for you.

**Comment by zierka** [comment]
Thank you, I will check it out!
