### ISSUE TITLE
The getter 'store' isn't defined for the class 'ImageCacheManager'.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [humblerookie/optimized_cached_image#29]
When trying to build my project, I'm getting this error. When I look into the code, it's right. I can't find `store` declared anywhere in this package. In fact, it's only mentioned in this function. How do I get around this?
> ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/optimized_cached_image-1.0.0/lib/image_cache_manager.dart:75:36: Error: The getter 'store' isn't defined for the class 'ImageCacheManager'.
>  - 'ImageCacheManager' is from 'package:optimized_cached_image/image_cache_manager.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/optimized_cached_image-1.0.0/lib/image_cache_manager.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'store'.
>       final orgCacheObject = await store.retrieveCacheData(parentUrl);
>                                    ^^^^^

**Comment by humblerookie** [comment]
This is most likely some issue with flutter upgrade/cache, could you provide the flutter doctor output?

**Comment by ThinkDigitalSoftware** [comment]
I believe this got fixed by deleting the package from pub cache and redownloading

**Comment by humblerookie** [comment]
Cool thanks
