### ISSUE TITLE
How to reload an image when it's loaded failed please?

### ISSUE THREAD

**Issue by kokocooler2020** [humblerookie/optimized_cached_image#32]
How to reload an image when it's loaded failed please?

I was listen on Function: errorWidget, when errorWidget was call, I refresh this widget by setState(), but image is not reload.

help and thank you~

**Comment by kokocooler2020** [comment]
> How to reload an image when it's loaded failed please?
> 
> I was listen on Function: errorWidget, when errorWidget was call, I refresh this widget by setState(), but image is not reload.
> 
> help and thank you~

**Comment by humblerookie** [comment]
Could you share the code you're using?

**Comment by humblerookie** [comment]
You'll have to use a stateful widget and use `setState` to change the source url being used by this widget. Perhaps a retry button `onTap`  is triggered.

**Comment by JoeCiou** [comment]
Hello, I am facing the problem, if the image is loaded failed on network disconnected case, when the network restored, how to reload the image without change the url?
