### ISSUE TITLE
StreamController (Bad state: Cannot add event after closing)

### ISSUE THREAD

**Issue by yenyichau** [humblerookie/optimized_cached_image#34]
This error triggered sometimes when I go to a new page with this plugin to call the image.

Plugin :
![Screenshot 2021-03-16 at 11 34 11 AM](https://user-images.githubusercontent.com/59037547/111252362-eb1abf80-864b-11eb-8edd-a274f3c35bd5.png)

StreamController :
![Screenshot 2021-03-16 at 11 34 36 AM](https://user-images.githubusercontent.com/59037547/111252370-ef46dd00-864b-11eb-8f76-2de0078fddb2.png)

Any idea how to fix this problem ? Thanks

**Comment by humblerookie** [comment]
Could you upgrade to the latest version? `2.0.0`?
