### ISSUE TITLE
Outdated Path_provider dependency

### ISSUE THREAD

**Issue by pumuckelo** [humblerookie/optimized_cached_image#35]
Hello, I got the following dependency issue. 

```
Because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 which depends on path_provider_windows ^2.0.0, shared_preferences >=2.0.0 requires path_provider_windows ^2.0.0.

And because optimized_cached_image >=2.0.0-dev.1 depends on path_provider ^1.6.18 which depends on path_provider_windows ^0.0.4, shared_preferences >=2.0.0 is incompatible with optimized_cached_image >=2.0.0-dev.1.
```

I think we just need to update the path_provider dependency

**Comment by Hannnes1** [comment]
I tried forking and updating, but I get an error saying that ``type '_File' is not a subtype of type 'File'`. So there might be more to do than just bumping the version in pubspec.

If anyone knows what the problem might be, I can give it another go.

**Comment by humblerookie** [comment]
Its not an issue with that package, essentially the flutter_cache_manager uses the `file` package which has conflicting name with the dart:io package File. Its silly but dart is shitty when it comes to compile-time safety checks. I'll fix this over the weekend

**Comment by humblerookie** [comment]
This issue is fixed via https://github.com/humblerookie/optimized_cached_image/pull/36. I've released a new version on pub
`2.0.0-dev.2`. Do give it a shot and let me know if the issue still persists for you.

**Comment by Hannnes1** [comment]
Works like a charm. Thank you for the quick update!

**Comment by pumuckelo** [comment]
@humblerookie awesome thank you!🎉
