### ISSUE TITLE
Support nullsafety

### ISSUE THREAD

**Issue by onethao** [humblerookie/optimized_cached_image#37]
Hi, 

Can you update pack support nullsafety?

Because optimized_cached_image >=2.0.0-dev.1 depends on octo_image ^0.3.0 and cached_network_image 3.0.0-nullsafety depends on octo_image ^1.0.0-nullsafety, optimized_cached_image >=2.0.0-dev.1 is incompatible with cached_network_image 3.0.0-nullsafety.
And because no versions of cached_network_image match >3.0.0-nullsafety <4.0.0, optimized_cached_image >=2.0.0-dev.1 is incompatible with cached_network_image ^3.0.0-nullsafety.
So, because onedanang depends on both cached_network_image ^3.0.0-nullsafety and optimized_cached_image ^2.0.0-dev.2, version solving failed.
pub get failed (1; So, because onedanang depends on both cached_network_image ^3.0.0-nullsafety and optimized_cached_image ^2.0.0-dev.2, version solving failed.)

Thanks

**Comment by humblerookie** [comment]
I'm sorry those are pre-release versions, and it would be premature to provide support for it. You may use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) if you wish to work with those.

**Comment by onethao** [comment]
yes, in understand but now need nullsafety with new version. Can you update?

**Comment by britannio** [comment]
@humblerookie It seems like all the dependencies of this package have migrated to null safety and thus this package is ready to be migrated. Will you be doing this?

**Comment by humblerookie** [comment]
@britannio I'm going to be busy this week, if you're comfortable contributing that would be great too.

**Comment by onethao** [comment]
@humblerookie These packages depend are fastest version support null safety. Can you update?
  octo_image: ^1.0.0
  flutter_cache_manager: ^3.0.0

**Comment by britannio** [comment]
> @humblerookie These packages depend are fastest version support null safety. Can you update?
>   octo_image: ^1.0.0
>   flutter_cache_manager: ^3.0.0
>   flutter_image_compress: ^1.0.0

Do you just need the dependencies to be updated now or do you also require this package to itself be null safe?

**Comment by onethao** [comment]
yes, update dependencies will support null safe.

**Comment by onethao** [comment]
It's working with optimized_cached_image: ^2.0.1. Thanks
