### ISSUE TITLE
Using optimized_cache_image in a hero causes flickering in latest version

### ISSUE THREAD

**Issue by amugofjava** [humblerookie/optimized_cached_image#40]
Hi @humblerookie,

I am using `optmized_cache_image` within a `Hero` widget to animate between two views. When I first used v1 of your package I noticed that the image would flicker during the animation. `optmized_cache_image` was trying to fetch a different sized version of the image during each frame of the animation which resulted in flickering and the placeholder appearing in some frames. I realised I hadn't set the height and width, so doing so fixed it. With version 2 of your package I have found the flickering is back and I can't work out what I have not set as the height and width fields are set. I hope that makes sense. The two videos below show the animation with v1 (before.mp4) and v2 (after.mp4) (slowed down to make it more obvious).

Do you have any idea or pointers as to where I can pinpoint the issue?

https://user-images.githubusercontent.com/5526902/112723534-fa7cf100-8f06-11eb-9ecc-5a368d3ba2ab.mp4

https://user-images.githubusercontent.com/5526902/112723603-58a9d400-8f07-11eb-9091-3898151e4c7a.mp4

Many thanks.

**Comment by humblerookie** [comment]
@amugofjava  consider using the latest version `2.0.1`. This should work as expected, you may provide `width`/`height` as earlier or even use `maxWidthDiskCache`/`maxHeightDiskCache`
