### ISSUE TITLE
Null-Safety support

### ISSUE THREAD

**Issue by jayjah** [humblerookie/optimized_cached_image#45]
I was wondering if you plan to support `null-safety` for this `optimized_cached_image` project?

**Comment by humblerookie** [comment]
I do plan to, but this might take a little time. I'll keep you posted.

**Comment by pumuckelo** [comment]
That would be awesome

**Comment by PfizerVaccine** [comment]
Yes please.

**Comment by Brazol** [comment]
@humblerookie Hi, any progress on this? Would love to use this one in our app but non-null-safety blocks us :/

**Comment by pumuckelo** [comment]
I'll try to take a look at it today as well. If I'm successful I'll create a pull request

**Comment by pumuckelo** [comment]
https://github.com/humblerookie/optimized_cached_image/pull/51 created a pull request

**Comment by egaga** [comment]
@pumuckelo I would like to try out this library as replacement for Cached Network Image but null-safety is blocking, so that would be appreciated.

**Comment by Termtime** [comment]
I would appreciate it too as I want to upgrade to null safety but the package is blocking.

**Comment by humblerookie** [comment]
Null safe version  `3.0.0` has been deployed, should be up in a bit.
https://github.com/humblerookie/optimized_cached_image/pull/52
