### ISSUE TITLE
flutter_cache_manager: '>=1.0.0 <=1.1.3'

### ISSUE THREAD

**Issue by Tizoner** [humblerookie/optimized_cached_image#6]
I can't use this package with audio_service package that uses flutter_cache_manager: '^1.2.2'.
Please remove upper bound dependency restriction.

**Comment by Tizoner** [comment]
When I've tried to manually remove restriciton, build failed.
But when I've changed flutter_cache_manager version of audio_service package to '^1.1.3' everything worked.
So you don't have to change code to remove this upper bound restriction.
The problem is not in your package.

**Comment by humblerookie** [comment]
Hi @Tizoner , 
The issue is really that 1.1.3 introduced breaking changes in flutter cache manager, I'll try updating the library this weekend to support the latest version.

**Comment by Tizoner** [comment]
Thank you, it would be great.
Your package allowed me to reduce images cache size by 10 times, while still keeping perfect image quality which is really cool.

**Comment by humblerookie** [comment]
I've just upgraded to the latest cache manager version https://github.com/humblerookie/optimized_cached_image/releases/tag/v0.1.10.
